### ISSUE TITLE
Foreign characters not supported in titles

### ISSUE THREAD

**Issue by QuickMythril** [Qortal/q-tube#25]
This issue may also apply to other Q-Apps.  See:  https://github.com/Qortal/qortal-ui/issues/272

In Q-Chat, someone reported that they were unable to use foreign characters (like Chinese) in various fields of some of the main Q-Apps, like Q-Tube and Q-Blog. They said that the fee was still processed and paid, but the publish failed and the content was not available. This information was also posted into the Q-Apps Development chat group, and is being reposted here so it doesn't get overlooked.

Also reported in Telegram:  https://t.me/qortal_official/133558
`I dont know who is responsable for Q-Tube but I would apreciate the ability to write special characters like ś ź ń ć ę ł ą and so on in the titles of the videos, as it is not possible now`

**Comment by QortalSeth** [comment]
Fixed by this PR: https://github.com/Qortal/q-tube/pull/30
